CREATE DATABASE IF NOT EXISTS authentication_db;
CREATE DATABASE IF NOT EXISTS albumdb_test;
CREATE DATABASE IF NOT EXISTS mediaservice_db;
CREATE DATABASE IF NOT EXISTS postdb_test;
CREATE DATABASE IF NOT EXISTS publicalbumdb_test;
CREATE DATABASE IF NOT EXISTS userdb_test;

CREATE USER 'user'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';
FLUSH PRIVILEGES;

CREATE USER 'connector_user'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'connector_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;



